# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d1cf21be9ebee5d166067327ebda4fac5be0f940b67a59102747330f42b4f8963d91ebaf0d53bb769e4fb58b8b4bb9eba3af31c2d688afd05e7792ce8d99e0e

test:
  secret_key_base: 8f2b701e80bf549139472700a29475247d7fbeb03db5710012eab4ba6366043225314bf7311a63443ea12827f3fd7e0f4028c7c2231c9c3b404f03b360ff6e15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
